stages:
  - test
  - deploy
env:
  global:
  - TRAVIS_RUST_VERSION=nightly
  - RUST_BACKTRACE=1
  - TWINE_USERNAME=pattonw

test_template: &test_template
  stage: test
  language: python
  python: 3.6
  before_install:
    source ./ci/travis/setup_rust.sh
  install:
    pip install -U tox-travis setuptools_rust
  script:
    ./ci/travis/test.sh

deploy_template: &deploy_template
  stage: deploy
  language: python
  sudo: required
  services:
    docker
  env:
    - CIBW_BUILD=cp35-*
  python: 3.6
  install:
    pip install -U cibuildwheel
  script:
    ./ci/travis/build.sh


jobs:
  include:
    - <<: *test_template
      python: 3.5
    - <<: *test_template
      python: 3.6
    - <<: *test_template
      python: 3.7
      dist: xenial
      sudo: required
    - <<: *deploy_template
      env:
        - CIBW_BUILD=cp35-*
    - <<: *deploy_template
      env:
        - CIBW_BUILD=cp36-*
    - <<: *deploy_template
      env:
        - CIBW_BUILD=cp37-*

