language: python
python:
  - 3.5

stages:
  - test
  - name: deploy
    if: tag IS present
env:
  global:
  - TRAVIS_RUST_VERSION=nightly-2019-07-01
  - RUST_BACKTRACE=1
  - PYPI_USERNAME=pattonw

test_template: &test_template
  stage: test
  before_install:
    source ./ci/travis/setup_rust.sh
  install:
    - make install-dev
  script:
    - make test

deploy_template: &deploy_template
  stage: deploy
  sudo: required
  install:
    pip install maturin==0.7.1b1
  script:
    maturin publish -i python --no-sdist -u PYPI_USERNAME -p PYPI_PASSWORD

# todo: sdist

jobs:
  include:
    - <<: *test_template
      python: 3.6
    - <<: *test_template
      dist: xenial
      python: 3.7
      sudo: required
    - <<: *deploy_template
      python: 3.6
    - <<: *deploy_template
      dist: xenial
      sudo: required
      python: 3.7
    - stage: deploy
      script:
        echo "skip"
      deploy:
        distributions: sdist
        password:
          secure: VeZNGpUs5ne3ZlCeZLPbT+3O6yRDM9sv8emg6m90ZwLuZAlXV0t2dGHKccMTBMbS2jWSy2q4TY2IkN0SOWrOmi53Klt3K5Y461Ra8dT+XdmXK8g+36HJEJKWfFvVpYVuIw72yoUWHZsr2iNxi7tiAc/AjBvbnbgSXuAayuVm+8K7tQ85kkfbdBErDQnhziEiqtIrjak3hwBgjWpm0UEuAKG/eTBFk0BAN9wqRajCS58WLaLVnF4FtAHT4QAxo33j99njB7cz8PLjXNd3BxT2BpMbjqmg8krVW7ayMJKdLvWdICezPB4nlsnL9jBlXMaRvI0ijSl59QkVCDbkrERUCR7IdJZqAX3IFSe+9X1cwzJsJeXYOfQjYMX+ZyqR8qcmQKS6M1u3uYMXhoj+TU9uO0sK4dNxrS0DRhg22TdjAcpqnz0UDVVWfFapltroE0ePVPs8aOOqdpJewRDPDI0ghRg/nzrSIhEI+85XnSTcjm4if5hwiEFchIFlV5d/ZIHtPn+b0fCRTDMq4kjObxD9uBbVvda1+CESCNrE91oB1erlrjygsDnpdRWi5dzaOVe5DJmAxT/V5mPFlskOPJLZr3lzZOQm1FGVJbvTN766plDCWozTAG8wT58hq/nJTBIiRjHlQnhFjlHLkaWTEq/jJ8mA++KXvbofCy833V0OMrw=
        provider: pypi
        user: pattonw
