language: python
python:
- 3.6
- 3.5

matrix:
include:
  - sudo: required
    services:
      - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
  - sudo: required
    services:
      - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
          PRE_CMD=linux32
env:
  global:
  - TRAVIS_RUST_VERSION=nightly
  - RUST_BACKTRACE=1
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - cmake
    - gcc
    - binutils-dev
    - libiberty-dev
before_install:
- source ./ci/travis/setup.sh
install: 
  - docker pull $DOCKER_IMAGE
  - pip install -U tox-travis cibuildwheel setuptools_rust


script:
  - docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis/build-wheels.sh
  - ls wheelhouse/
  - if [[ $TRAVIS_TAG ]]; then
  -    $PIP install twine
  -    $PYTHON -m twine upload wheelhouse/*.whl
  -  fi