[package]
name = "pyn5"
version = "0.1.0"
authors = ["pattonw <pattonw@hhmi.org>"]

[lib]
name = "pyn5"
crate-type = ["dylib"]

[dependencies]
cpython = { version = "0.1", features = ["extension-module"] }
n5 = { version = "0.2", default-features = false, features = ["filesystem", "gzip", "use_ndarray"]}
